### ISSUE TITLE
T1M appears to produce incorrect results for some contractions

### ISSUE THREAD

**Issue by willnerNCP** [MatthiasReumann/TFCTC#8]
Hey there, 
I'm currently testing/benchmarking T1M against my Loop-over-GEMM and TTGT Implementation, and I noticed some discrepancies in the contraction results. I test using the following formula
![Image](https://github.com/user-attachments/assets/5d598f94-467f-4948-aa1d-fb3223701080)
which is a slightly stricter generalization of Eq 3.13, N. J. Higham. “Accuracy and stability of numerical algorithms” to tensors. 
If the estimator yields values smaller than 1, the two implementations can be considered equal up to numerical errors, otherwise one of the implementations is faulty.

In the following minimal working example, I'm checking contraction (3, 2, 3) for memory layout "abc cd abd", against a reference implementation. As "abc cd abd" can be formulated in terms of a single GEMM, this is what im testing against.
```cpp
#include <t1m.hpp>
#include <cblas.h>
#include <spdlog/spdlog.h>

double norm(double* X, size_t size) {
  return cblas_dnrm2(size, X, 1);
} 

void init(double* X, size_t size) {
  for(int i = 0; i < size; i++) X[i] = static_cast <double> (rand()) / static_cast <double> (RAND_MAX);
}

int main(){
  for (size_t dim = 2; dim < 20; dim++) {
    double *A = nullptr, *B = nullptr, *C_T1M = nullptr, *C_REF = nullptr;
    size_t sizeA = dim * dim * dim;
    size_t sizeB = dim * dim;
    size_t sizeC = dim * dim * dim;
    t1m::utils::alloc_aligned(&A, sizeA);
    t1m::utils::alloc_aligned(&B, sizeB);
    t1m::utils::alloc_aligned(&C_T1M, sizeC);
    t1m::utils::alloc_aligned(&C_REF, sizeC);
    init(A, sizeA);
    init(B, sizeB);
    init(C_T1M, sizeC);
    init(C_REF, sizeC);

    auto tensorA = t1m::Tensor<double>({dim, dim, dim}, A);
    auto tensorB = t1m::Tensor<double>({dim, dim}, B);
    auto tensorC = t1m::Tensor<double>({dim, dim, dim}, C_T1M);

    t1m::contract(1.0, tensorA, "abc", tensorB, "cd", 0.0, tensorC, "abd");

    size_t incColA = dim * dim;
    size_t incColB = dim;
    size_t incColC = dim * dim;
    size_t m = dim * dim;
    size_t n = dim;
    size_t k = dim;

    // A[ab, c] * B[c, d] = C[ab, d];
    cblas_dgemm(CblasColMajor, CblasNoTrans, CblasNoTrans,
      m, n, k, 
      1.0, A, incColA, B, incColB,
      0.0, C_REF, incColC);

    cblas_daxpy(sizeC, -1.0, C_T1M, 1, C_REF, 1); // C_REF = C_REF - C_T1M
    auto estimator = norm(C_REF, sizeC) / (std::numeric_limits<double>::epsilon() * dim * norm(A, sizeA) * norm(B, sizeB));
    spdlog::info("dim {}: norm_diff {}, estimator {}", dim, norm(C_REF, sizeC), estimator);
    
    free(A);
    free(B);
    free(C_T1M);
    free(C_REF);
  }

}
```
which yields 
```
dim 2: norm_diff 1.8573932929747787, estimator 2170774917388281
dim 3: norm_diff 2.484108490286804, estimator 662516711199772.5
dim 4: norm_diff 4.248283563890615, estimator 389976716244265.94
dim 5: norm_diff 6.811071378526189, estimator 343559318026866.06
dim 6: norm_diff 0, estimator 0
dim 7: norm_diff 8.18593368771288, estimator 117351238906580.22
dim 8: norm_diff 9.075664513335767, estimator 88867005612301.25
dim 9: norm_diff 9.367344947982971, estimator 61841323664363.58
dim 10: norm_diff 16.729570089583614, estimator 73252804343287.73
dim 11: norm_diff 24.45573911308585, estimator 76329688217682.98
dim 12: norm_diff 23.760261230757965, estimator 55259428745882.914
dim 13: norm_diff 40.088933667879985, estimator 67565981706589.08
dim 14: norm_diff 43.09527707209205, estimator 54139544673956.83
dim 15: norm_diff 41.31990195450511, estimator 45389218107827.59
dim 16: norm_diff 57.088116391831704, estimator 44784401390685.63
dim 17: norm_diff 68.4596933921457, estimator 44532305647296.805
dim 18: norm_diff 69.01394682868884, estimator 37337203253431.43
dim 19: norm_diff 83.82919110117942, estimator 37809304738473.77
```
This seems to happen for any memory layout of (3, 2, 3), (3, 3, 4), (4, 3, 3) and (4, 4, 4). (3, 3, 2) and (2, 2, 2) work perfectly fine. As far as I could tell, C_T1M & C_REF coincide on most entries, except on some of the trailing ones, i.e. I suspect multiplication of trailing tensor blocks is faulty.
Can you reproduce this behaviour on your machine ?

Cheers, Marius

**Comment by MatthiasReumann** [comment]
Hey Marius! Thanks for pointing out this issue!

Yes, while working on #6 I've noticed some problems too. Should be fixed once #6 is merged - which should happen sometime in the next two weeks.

Would be interesting if this bug also occurs for complex numbers. If possible, could you run the same test with complex numbers? **Thanks!**

**Comment by MatthiasReumann** [comment]
Moreover, I just realized that your code initializes the `C` tensor with random values. As of now, `t1m` requires the `C` tensor to be initialized with zero. See [`test_real.cpp`](https://github.com/MatthiasReumann/t1m/blob/99d4bc07406fcf32f8225fdf2acb43d94cb89efb/test/test_real.cpp) for an example.

**Comment by willnerNCP** [comment]
Ah okay, thanks for the info! Actually I have a testing suite that tests all memory layouts of (3, 2, 3), (3, 3, 4), (4, 3, 3), (4, 4, 4), (3, 3, 2) and (2, 2, 2) for the all BLAS data types and different contraction methods (LOG, TTGT, T1M). I just noticed that float32 always works, whereas double, complex float and complex double fail for anything but (3, 3, 2) and (2, 2, 2). This is an oddly specific behaviour, as your real version of T1M gemm is templated. I tried aligning datapointers to 64 instead of 32 (just an idea), but nothing changed.
Initializing C by zero does not fix the problem in general, but for the reference code I sent you, modifying the respective lines
```
init0(C_T1M, sizeC);
init0(C_REF, sizeC);
```
where
```
void init0(double* X, size_t size) {
  std::memset(X, 0, sizeof(double)/sizeof(char)*size);
}
```
makes it work up until dimension 8, ie.
```
dim 2: norm_diff 0, estimator 0
dim 3: norm_diff 0, estimator 0
dim 4: norm_diff 0, estimator 0
dim 5: norm_diff 0, estimator 0
dim 6: norm_diff 0, estimator 0
dim 7: norm_diff 0, estimator 0
dim 8: norm_diff 0, estimator 0
dim 9: norm_diff 6.6366406545935215, estimator 39381985627490.625
dim 10: norm_diff 11.46196017097785, estimator 53280599658750.45
dim 11: norm_diff 17.381548135854633, estimator 56121509730596.82
dim 12: norm_diff 21.31808764333707, estimator 50344760883242.1
dim 13: norm_diff 33.880336366265986, estimator 58524887816898.27
dim 14: norm_diff 34.447841323836656, estimator 47478827219866.45
dim 15: norm_diff 42.34671817512732, estimator 44064644198575.92
dim 16: norm_diff 53.851011691717005, estimator 43306497586939.3
dim 17: norm_diff 55.75959015881958, estimator 37282305155340.48
dim 18: norm_diff 64.1955757975852, estimator 36887958472841.07
dim 19: norm_diff 79.37002167401444, estimator 36147610370077.47
```

Hope this helps :) I'm glad you're still actively working on the project, because I feel T1M is really promising, but also no pressure from my side, take your time. 
Cheers, Marius

**Comment by MatthiasReumann** [comment]
Hey @willnerNCP !

Brief Update: The real valued contractions should be fixed. If you want to benchmark them, simply use the current version of the #6 branch. I haven't gotten to the 1M packing kernels yet. However, plan do to so soon.

**Comment by MatthiasReumann** [comment]
The bug should now be fixed 🚀 You could please pull #6 and verify that on your end? 

Please take also a look at the README.md since the interface changed a bit.

Thanks again for pointing out this issue!

**Comment by willnerNCP** [comment]
Hey there,

I integrated #6 into my benchmarks, which went quite smoothly. I like what you did with the CMake interfacing.
Sadly in its current version, T1M segfaults on my machine for any contraction, as well as for the example you give in the README. The segfaults happens within the blis kernels, ie bli_dgemm_haswell_asm_6x8 or bli_sgemm_haswell_asm_6x16 respectively. Ill try it on another machine some time next week :)
In the mean time, I have some additional suggestions:
* Remove the unused print include in packing.h to make the lib compatible with C++20
* The apt version of blis (libblis-dev) has the blocksize parameter functions expect cntx_t* without the const (dont ask me why). If you want to support that version to, I suggest removing const qualifiers in get_block_sizes and doing something like `cntx_t* cntx = const_cast<cntx_t*>(bli_gks_query_cntx());` in l. 25 of T1M.h.
* 
Cheers, Marius

Edit: the segfaults happened for both the manual installation of BLIS and the apt version (compiled with fpermissive to allow for the const dismissing).

**Comment by MatthiasReumann** [comment]
@willnerNCP Thanks again! 🙌🏼 Appreciate your help.

I adjusted the code accordingly. 

----

> Sadly in its current version, T1M segfaults on my machine for any contraction [...]

That is really interesting. 

Since it worked previously, I have a gut feeling that the problem are the block sizes (I replaced `bli_cntx_get_l3_sup_blksz_def_dt` with `bli_cntx_get_blksz_def_dt`). Could you maybe print the block sizes on your machine? Because, the funny thing is, if I use `bli_cntx_get_l3_sup_blksz_def_dt` on my M1 Air, all block sizes are initialized with some constant large number. That (kind of) makes sense since according to their documentation `bli_cntx_get_l3_sup_blksz_def_dt ` doesn't guarantee to have default values.

**Comment by willnerNCP** [comment]
I printed the locals in t1m::contract using gdb. As far as I can tell, nothing looks out of the ordinary. 

```
Program received signal SIGSEGV, Segmentation fault.
0x000055555556f7b5 in bli_sgemm_haswell_asm_6x16 ()
(gdb) up 2
#2  0x000055555555cd42 in t1m::contract<std::complex<float>, 3ul, 2ul, 3ul> (a=..., labels_a="abc", b=..., labels_b="bd", c=..., labels_c="acd")
    at /home/marius/tartarus/build/_deps/t1m-src/include/t1m/t1m.h:191
191                 gemm_kernel<T>(m, n, k_real, &alpha, sliver_a, sliver_b, &beta,
(gdb) info locals
m = 6
cri = 0
sliver_a = 0x7ffff73d9010
view_c = {rs = std::span of length 3 = {0, 1, 2}, cs = std::span of length 2 = {0, 4}, br = 6, rbs = std::span of length 1 = {1}, bc = 16, 
  cbs = std::span of length 1 = {4}}
i_r = 0
n = 2
cci = 0
sliver_b = 0x7ffff7403010
j_r = 0
mc_m = 4
mc_m_real = 8
view_a = {rs = std::span of length 4 = {0, 1, 4, 5}, cs = std::span of length 2 = {0, 2}, br = 6, rbs = std::span of length 1 = {0}, bc = 4, 
  cbs = std::span of length 1 = {2}}
i_c = 0
k = 2
k_real = 4
view_b = {rs = std::span of length 2 = {0, 1}, cs = std::span of length 2 = {0, 2}, br = 4, rbs = std::span of length 1 = {1}, bc = 16, 
  cbs = std::span of length 1 = {2}}
p_c = 0
nc_n = 2
j_c = 0
cntx = 0x5555556a7410
bs = @0x7fffffffd3c0: {MR = 6, NR = 16, KP = 4, MC = 168, KC = 256, NC = 4080}
MR = 6
NR = 16
KP = 4
MC = 168
KC = 256
NC = 4080
bundles = {CI = std::vector of length 2, capacity 2 = {0, 1}, CJ = std::vector of length 1, capacity 1 = {2}, AI = std::vector of length 2, capacity 2 = {0, 
    2}, AP = std::vector of length 1, capacity 1 = {1}, BP = std::vector of length 1, capacity 1 = {0}, BJ = std::vector of length 1, capacity 1 = {1}}
layout_a = {rs = std::vector of length 4, capacity 4 = {0, 1, 4, 5}, cs = std::vector of length 2, capacity 2 = {0, 2}, br = 6, 
  rbs = std::vector of length 1, capacity 1 = {0}, bc = 4, cbs = std::vector of length 1, capacity 1 = {2}}
layout_b = {rs = std::vector of length 2, capacity 2 = {0, 1}, cs = std::vector of length 2, capacity 2 = {0, 2}, br = 4, 
  rbs = std::vector of length 1, capacity 1 = {1}, bc = 16, cbs = std::vector of length 1, capacity 1 = {2}}
layout_c = {rs = std::vector of length 4, capacity 4 = {0, 1, 2, 3}, cs = std::vector of length 2, capacity 2 = {0, 4}, br = 6, 
  rbs = std::vector of length 1, capacity 1 = {1}, bc = 16, cbs = std::vector of length 1, capacity 1 = {4}}
matr_a = {rs = std::span of length 4 = {0, 1, 4, 5}, cs = std::span of length 2 = {0, 2}, br = 6, rbs = std::span of length 1 = {0}, bc = 4, 
  cbs = std::span of length 1 = {2}}
matr_b = {rs = std::span of length 2 = {0, 1}, cs = std::span of length 2 = {0, 2}, br = 4, rbs = std::span of length 1 = {1}, bc = 16, 
  cbs = std::span of length 1 = {2}}
matr_c = {rs = std::span of length 4 = {0, 1, 2, 3}, cs = std::span of length 2 = {0, 4}, br = 6, rbs = std::span of length 1 = {1}, bc = 16, 
  cbs = std::span of length 1 = {4}}
space_size_a = 43008
space_size_b = 1044480
space_size_c = 96
space_total = 1087584
alloc = {<std::__new_allocator<float>> = {<No data fields>}, <No data fields>}
space_a = 0x7ffff73d9010
space_b = 0x7ffff7403010
space_c = 0x7ffff77ff010
alpha = 1
beta = 0
data = {schema_a = 4159153752, schema_b = 32767, a_next = 0x7fffffffd9c0, b_next = 0x2e78786362696c67, is_a = 7813586406938797358, is_b = 140737488345896, 
  ps_a = 140737352483736, ps_b = 140737488345712, off_m = 140737353982830, off_n = 140737351930006, ukr = 0x49, params = 0x10}
M = 4
K = 2
N = 2
```

Also changing to `bli_cntx_get_l3_sup_blksz_def_dt` does not alter the blocksizes at all on my system.

**Comment by MatthiasReumann** [comment]
~~I potentially fixed the problem.~~ Would you mind testing it again with the latest version of #6 ? Thanks! 🙌🏼

btw: what compiler are you using?

~~Edit: I just got access to a haswell machine and it still segfaults. Will keep you posted on this.~~

Edit 2: Should be fixed now. As you can see in the gdb output above. The `data: auxinfo_t` struct is filled with data. This struct should be empty when calling the kernel 🫠

**Comment by willnerNCP** [comment]
Hey, I'm still getting the segfaults with your newest version. I'm using gcc version 13.3.0 and compiling for C++20 (tho 23 does not work either). 
Did you post the gdb output you're referring to? 
Anyways, if you got it working on a haswell machine, it might be a problem on my side. Ill test it on friday on some other machines.

**Comment by MatthiasReumann** [comment]
> Hey, I'm still getting the segfaults with your newest version. I'm using gcc version 13.3.0 and compiling for C++20 (tho 23 does not work either).

Mhm, interesting. I'm compiling with clang / LLVM. Would be interesting to see if the problem persists by changing the compiler. 

Edit: Doesn't persist for the haswell-based compute node that I use for gcc@13.3.0.

You said it also fails for the minimal example, right? 

> Did you post the gdb output you're referring to? 

I was referring to the gdb output you posted. 

> Anyways, if you got it working on a haswell machine, it might be a problem on my side. I'll test it on friday on some other machines.

That would be great. Many thanks 🙇🏻

**Comment by willnerNCP** [comment]
Hey, sry for the late response. 
I tried running the code on different machines (Ubuntu 22 and 24) and with different compilers (gcc 13.3, gcc 14.2, linux clang 19), and sadly had no success. Still getting the segfault in the blis gemm kernels, also for the minimal example.

Im kinda clueless at this point. You said you got it running on your haswell compute node ? How did you build ?
Im doing 
```
find_package(OpenMP REQUIRED)
find_library(BLIS_LIBRARIES "libblis.a" REQUIRED)
find_path(BLIS_INCLUDE_DIRS "blis.h" REQUIRED)
FetchContent_Declare(
    t1m
    GIT_REPOSITORY https://github.com/MatthiasReumann/t1m.git
    GIT_TAG enh/refactor-to-modern-cpp
)
FetchContent_MakeAvailable(t1m)

add_executable(main main.cpp)
target_link_libraries(main ${BLIS_LIBRARIES} -fopenmp t1m)
```
with main.cpp containing the minimal example.

**Comment by MatthiasReumann** [comment]
@willnerNCP Mhm. That's strange indeed. One thing I notice is that you link with OpenMP - which I don't since I removed multithreading (for now). 

I've added the minimal working example to the repository. Could you maybe try to building the example of the project repo itself by using `"-DT1M_BUILD_EXAMPLE=ON"`. 

Essentially, running
```terminal
$ git clone https://github.com/MatthiasReumann/t1m.git
$ cd t1m
$ git switch enh/refactor-to-modern-cpp
$ CXX=... cmake -B build -DT1M_BUILD_EXAMPLE=ON .
$ cd build
$ cmake --build . --config Release --target example_t1m
$ ./example/example_t1m
```

If this still doesn't work, I will try to get access to another machine. 

Thanks again for your patience and willingness to work this out! 🙌🏼

**Comment by MatthiasReumann** [comment]
Update: Just tried to run both the example and the tests on a Ubuntu Compute Node with Zen3 architecture. I cloned, built, and installed BLIS by hand. Everything works fine.

**Comment by willnerNCP** [comment]
Finally I have some good news: cloning and building t1m by itself like you proposed works for me too !
FYI, I was also cloning and installing BLIS manually using the auto config.

Still riddles me, why the fetchcontent variant wouldn't work (even though it previously did...). I'll keep you updated, but I guess this is no longer a problem on your side :) Thanks for all the help.

**Comment by MatthiasReumann** [comment]
Oh wow! That's great 🚀 (and confusing)

I will try the FetchContent method on my available machines too. Maybe we can figure out the problem together - because this really should work. 

Then I will also probably merge #6, so you might want to use the main branch soon.

Thanks again 🙇🏻

**Comment by willnerNCP** [comment]
Okay, I have some new information:
I noticed that the benchmarks still segfault (when building with T1M_BUILD_BENCHMARK=ON). Apparently, on my machine, example and tests only work because of -fsanitize=address.
Heres what I did:
```
$ git clone https://github.com/MatthiasReumann/t1m.git
$ cd t1m
$ git switch enh/refactor-to-modern-cpp
$ cd example
$ g++ -std=c++23 -fsanitize=address -I ../include example.cpp /usr/local/lib/libblis.a 
$ ./a.out 
[works]
$ g++ -std=c++23 -I ../include example.cpp /usr/local/lib/libblis.a 
$ ./a.out 
Segmentation fault (core dumped)
```
Can you reproduce this behavior on your Ubuntu machine ?

**Comment by MatthiasReumann** [comment]
> Okay, I have some new information: I noticed that the benchmarks still segfault (when building with T1M_BUILD_BENCHMARK=ON). Apparently, on my machine, example and tests only work because of -fsanitize=address. Heres what I did:
> 
> ```
> $ git clone https://github.com/MatthiasReumann/t1m.git
> $ cd t1m
> $ git switch enh/refactor-to-modern-cpp
> $ cd example
> $ g++ -std=c++23 -fsanitize=address -I ../include example.cpp /usr/local/lib/libblis.a 
> $ ./a.out 
> [works]
> $ g++ -std=c++23 -I ../include example.cpp /usr/local/lib/libblis.a 
> $ ./a.out 
> Segmentation fault (core dumped)
> ```
> 
> Can you reproduce this behavior on your Ubuntu machine ?

Oh wow. Yes! That's interesting.

**Comment by MatthiasReumann** [comment]
~~Using `-static-libasan` shows that it has something to do with allocations. I will take a look, open a new branch, and notify you.~~ Edit: Seems to be unrelated.

Could you compile with `-static-libasan` and take a look at the output?

**Comment by willnerNCP** [comment]
Address sanitizer gives me no output/errors for example.cpp, also when compiling with `-static-libasan -fsanitize=address`.
I did however find another weird phenomenom: 
Valgrinding makes both versions (the one with `-fsanitize` and the one without) run without segfault on my machine. This itself is not too unexpected, as we're dealing with UDB. However the version with `-fsanitize` shows no memory allocated at all on exit, whereas the other version has some still reachable pointers, which were originally allocated by `bli_gks_query_cntx` as seen by passing `--leak-check=full --show-leak-kinds=all` to valgrind. 
This might be a coincidence, or maybe it points towards the issue.

Edit: It seems that `-fsanitize` just makes valgrind stop working, so probably unrelated.

**Comment by MatthiasReumann** [comment]
@willnerNCP 👋🏻

I have good news: Pull request #9 should fix the issue (It is already merged into `main`). As it seems BLIS does require 64bit aligned memory addresses. Whilst refactoring, I thought this is not necessary since it worked on my machines. Seems to be a wrong assumption.

Could you maybe verify on your end that the bug is fixed also? Thanks! 🚀

**Comment by willnerNCP** [comment]
Yayayay it works :D finally. my testing suite passed for all dtypes and memory layouts of the contraction cases (2, 2, 2) , (3, 3, 2), (3, 2, 3), (3, 3, 4), (4, 3, 3) and (4, 4, 4). Thanks a lot again :)

**Comment by MatthiasReumann** [comment]
Again: **Thanks** for your participation, time, and energy 🙇🏻. 
I will close this issue now 🪦
